### PR TITLE
fix for #331

### PR DESCRIPTION
**Pull request by goruck**
See #331 for details.

### CODE REVIEW

**Comment by rbaynes** [comment]
@goruck I made a few changes to your code and made a new PR #335 
so I am closing this one and waiting for @Spaghet to review 335.

**Comment by Spaghet** [comment]
:| I feel like he deserves some recognition for the work he put in so I'd be more comfortable if you just added your changes on top of this PR @rbaynes, unless @goruck is fine with it. 

Looked through both PRs and they look ok, just going to sit on this for a bit

**Comment by rbaynes** [comment]
Good point @Spaghet.   Sorry @goruck I didn't want to steal the great work you have done, I only wanted to make a few changes to your work.

@Spaghet please just accept one of the PRs and I'll go from there.  I need this merged in so I can complete the release process.

**Comment by goruck** [comment]
@rbaynes no worries! Thanks for the opportunity to contribute! BTW, I live in Silicon Valley so sadly I can't take you up on the dev offer. But that won't stop me from working on this great project :)

**Pull request merged**
