### PR TITLE
New recipe format called flexformat + more tests

### PR DESCRIPTION
**Pull request by rwdavis513**
This new recipe format allows for any complexity that the simple recipe format can provide, but with the smaller file size of phased recipes. 

Recipe Format structure:
phase:
    step: { 
         variable: [start_time, end_time, value] 
    }

The phases can be repeated as many times as needed as well as the steps. Each step is ideally a 24 hour period.

See `openag_brain/data/mock_recipes` for an example

This new format is compatible with the cloud software.

### CODE REVIEW

**Comment by rwdavis513** [comment]
Note: The CouchDB setup on the PFC needs to allow for the recipes database to have a phases field instead of operations (or we could update the new format to use operations instead of phases).

`couchdb.http.ServerError: (403, (u'forbidden', u'Recipe instances are required to have a operations field'))`

**Comment by rbaynes** [comment]
Some suggestions:

1. If we use "operations" instead of "phases" in the JSON of a recipe, we avoid the DB change.
1. There are existing recipes and users currently using a recipe with the format name of "phased".  I think we should pick a new name for this new format to avoid confusion.  Perhaps call this new format "detailed" or anything you like.
1. Thanks for breaking things up into their own files.
1. I intended TRACE/trace() to be per node, but rospy.logdebug() does that already, so it will work.
1. After reviewing my changes to the tests (PR 267) and merging to master, can we merge those changes into this branch?

**Comment by rwdavis513** [comment]
@rbaynes I merged your changes from [PR267](https://github.com/OpenAgInitiative/openag_brain/pull/267) this PR. I agree a different name would be better. I started with "phased_dense" as it is a phased recipe that can contain a dense amount of information. I'd be glad to change it to anything else though. Unfortunately, I used the name quite a few places so I'll need to go back through to update the name to something else.

**Comment by rwdavis513** [comment]
@rbaynes It looks like it would take the cloud team about a day to change from phases to operations, so I'll look into updating the couchdb to handle both for now or remove the restriction.

**Comment by rwdavis513** [comment]
@rbaynes I updated the recipe name to "flexformat" to create a bigger difference from the prior recipe formats. Rather than changing "phases" to "operations" I'd like to remove the "operations" requirement check from the couchdb doc database. This is a simple one line change.  See [openag_python PR#41](https://github.com/OpenAgInitiative/openag_python/pull/41)

**Comment by rwdavis513** [comment]
This should be ready to be merged into master. Let me know if you see anything else. Thanks!

**Comment by rwdavis513** [comment]
Addresses Issue [#194](https://github.com/OpenAgInitiative/openag_brain/issues/194)

**Comment by rbaynes** [comment]
Love the "flexformat"  💪

**Comment by Spaghet** [comment]
Is there a reason there are variable units in the recipe? We already have that information in the var_types param server which will allow us to maintain a single reference point to what we mean when we say "light_illuminance" or whatnot. We have a problem where we declare the same thing in multiple places and they all need to sync up.

**Pull request merged**
